FROM elastic/filebeat:8.17.4
COPY filebeat/filebeat.yml /usr/share/filebeat/filebeat.yml
USER root
RUN chown root:filebeat /usr/share/filebeat/filebeat.yml && chmod 0640 /usr/share/filebeat/filebeat.yml
USER filebeat
